// ============================================================
// Fresh lines: twenty more things for everyone to say, keyed to where they are in their story and the day count.
// fresh(id, base) merges a character's usual filler with these, avoiding anything they have said recently.
// ============================================================
const L_ = (t, need, d0, d1) => ({ t, need, d0: d0 || 1, d1: d1 || 99 });
const FRESH = {
  amos: [
    L_("Rain's the same rain every day. It just lands on different people.", () => G.chars.amos.stage < 2),
    L_("I had a dog once. Dog had a better coat than me. That's a joke; it was a good dog.", () => G.chars.amos.stage < 3),
    L_("You count the cars. Reds, then blues. When you get to twenty blues it's noon. It works.", () => G.chars.amos.stage < 2),
    L_("Guy walked past this morning and dropped a quarter and picked it back up. Looked right at me while he did it.", () => G.chars.amos.stage < 2),
    L_("Library's warm till five. After five it's a library that's closed. I know the difference in my knees."),
    L_("Twenty-two years on roofs. You'd think I'd know rain. I don't. I just know roofs."),
    L_("The girl at Lin's drew me. Didn't ask. I saw it on the counter. I looked like somebody's father.", () => G.chars.mei.sketch),
    L_("Nadia sent a coffee down. I didn't ask. That's the thing about the ones who send it: you didn't ask.", () => G.chars.nadia.stage >= 1),
    L_("The nurse in your building stops. Doesn't give anything. Just stops. I'll take a stop.", () => G.chars.nora && G.chars.nora.met),
    L_("The foreman's a hard man. Hard's fine. Hard's honest. It's the soft ones that don't pay you.", () => G.chars.amos.job === 'dock'),
    L_("Six a.m. sharp. I'm there at five-thirty. I like being there before the day knows I'm coming.", () => !!G.chars.amos.job),
    L_("Got a key. A key! I turn it twice a night just to hear it.", () => G.chars.amos.room),
    L_("Boiler's got a rhythm. Two knocks, a sigh. I named it. I'm not telling you what.", () => G.chars.amos.room),
    L_("You're thinner. I say that as a man who knows thin from the inside."),
    L_("I don't ask what's wrong with you. You'll tell me or you won't. Either way I'll be here.", null, 30),
    L_("Sundays the whole street empties out like somebody pulled a plug. Then Monday fills it back up.", () => G.day % 7 === 0),
    L_("The old man on the bench. Walter. He nodded at me once. Once in a year. I've kept it.", () => !G.chars.walter.dead),
    L_("The bench is empty. I keep looking at it like it's going to explain itself.", () => G.chars.walter.dead),
    L_("There's a kid on the corner some mornings. Hood up. Looks at the poster on Sol's wall like it owes him money.", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("Go on. Go home. You look like the day's had enough of you.", null, 60),
  ],
  mei: [
    L_("Mom rearranged the cans again. By color. She says it's for the customers. It's for her.", () => !G.chars.mei.cold),
    L_("I drew the dumpster. Three times. It's the most honest thing on the street.", () => G.chars.mei.stage >= 1),
    L_("The rain makes the window a mirror after four. I draw whoever's in it. Mostly me. Sometimes you."),
    L_("If you buy the day-old bread I'm supposed to charge you. I'm not going to. Don't tell Mom.", () => G.chars.mei.stage >= 2),
    L_("The delivery bags are terrible. I've written to the company. The company does not write back."),
    L_("Mom asked who you were. I said a regular. She said regulars don't stand like that. I don't know what that means.", null, 5, 40),
    L_("Amos said you're sick. Are you? You don't have to say. I drew you anyway.", () => G.chars.amos.met, 20),
    L_("There's a woman at the diner who tips in quarters and apologizes for every one. I want to draw her hands.", () => !G.chars.nadia.closed),
    L_("The nurse from your building buys one orange. One. Every day. I've started keeping the good one back.", () => G.chars.nora && G.chars.nora.met),
    L_("I'm not going to talk about the application. I'm going to ring you up and not talk about it.", () => G.chars.mei.applied && !G.chars.mei.accepted),
    L_("Orientation packet came. There's a map. I've never needed a map for anything in my life.", () => G.chars.mei.accepted),
    L_("The pawn shop has a trumpet in the window. I drew it. Sol saw me. He didn't say anything. He moved it into better light.", () => G.chars.sol && G.chars.sol.met),
    L_("Mrs. Ortega tried to pay for oranges with tamales. Mom took the deal. Mom never takes a deal."),
    L_("You know what nobody draws? Ceilings. I'm going to be the ceiling person."),
    L_("The 14 runs Sundays now. I saw it. I thought Walter was making it up.", () => G.day >= 8),
    L_("The lost poster's gone from Sol's wall. Somebody peeled it off carefully. That's a good sign or a bad one; I can't tell.", () => G.chars.theo && G.chars.theo.reunited),
    L_("Bread's five. I know. I'd make it three if it was mine. It's not mine. Someday something's going to be mine."),
    L_("I get forty minutes between the lunch rush and the school kids. That's my whole studio. Forty minutes."),
    L_("You look tired. Not the normal kind. I'm going to draw the normal kind on you anyway.", null, 50),
    L_("Don't die before the show. That's not a joke. I don't know what it is. Don't.", () => G.chars.mei.accepted, 70),
  ],
  walter: [
    L_("Ruth set her watch by the 14. When they cut it she kept setting it. Twelve minutes. Nothing came. She didn't mind."),
    L_("The Herald ran a story about this block once. 1979. I set the type. Every word. I could recite it and I won't."),
    L_("My cane is older than you. I'm certain of that. It was my father's and it disliked him too."),
    L_("The girl at the market draws. I've seen her at it through the glass. Someone should tell her she's good. Not me; I'm a stranger."),
    L_("That man by the stoop. Reed? He nodded at me. I nodded back. That's a whole friendship at our age.", () => !G.chars.amos.dead),
    L_("Nadia's coffee is terrible. I say that with love. Ruth's was worse."),
    L_("I've got seven clocks in the house and I don't wind any of them. It's quieter that way. Ruth wound them."),
    L_("Sundays I take the long way to Ruth. Past the mill. Past the school. It takes all day. That's the point.", () => G.day % 7 !== 0),
    L_("The 14 runs Sundays. Did you know that? The one day I'm not here to see it. That's the city for you."),
    L_("You're coughing more. I'm not a doctor. I've buried enough people to know a cough."),
    L_("Chess is a conversation with someone who isn't lying to you. That's rarer than it sounds.", () => G.chars.walter.chess),
    L_("Radio's got a man calling ball games I don't follow. I follow him. His voice. It's Ruth's brother's voice, near enough.", () => G.chars.walter.radio),
    L_("I don't need the bus. I have never needed the bus. I need somewhere to be expected."),
    L_("There's a photograph on my mantel of a woman laughing at something I said in 1962. I don't remember what I said. She remembered."),
    L_("The stone next to hers is paid for. I did that in March. It's a strange thing to shop for. The man was very kind."),
    L_("The nurse from your building sat here Tuesday. Didn't say a word. Best conversation I've had all month.", () => G.chars.nora && G.chars.nora.trust >= 2),
    L_("The typesetter's disease is you read everything backwards. Signs. Menus. Faces, sometimes."),
    L_("My house is four doors off the river. Blue. Ruth chose the blue. I have repainted it blue twice since and it's never been right."),
    L_("I'm not lonely. I want to be clear. I'm waiting. They look alike from the sidewalk."),
    L_("Sit a while longer. It's not a request. It's an old man's whole strategy.", null, 40),
  ],
  nadia: [
    L_("Sam's teacher says he reads above his level. I said what level is that. She said yours. I laughed. I shouldn't have."),
    L_("The health inspector comes Thursdays. He orders the pie. He gives me a B. Every time. I've stopped asking."),
    L_("Walter says the pie's terrible. It's my father's recipe. It is terrible. That's why people order it.", () => !G.chars.walter.dead),
    L_("The old man's bench is empty. I keep a slice back anyway. Habit. Habit's most of a business."),
    L_("The 412's on the board now. People ask what's in it. I say a neighbor. They think it's a joke.", () => G.flags.freeSoup),
    L_("Amos runs the back like it's a ship. I don't know where he learned it. Roofs, he says. I don't ask.", () => G.chars.amos.job === 'diner'),
    L_("The nurse from your building comes at midnight and eats pie standing up. I've stopped offering a stool.", () => G.chars.nora && G.chars.nora.met),
    L_("The girl from Lin's drew the counter. She put me in it, wiping. I'm always wiping. I didn't know that till I saw it."),
    L_("Sixty covers a day, once. Now I count them on one hand and have fingers left. Don't tell the landlord."),
    L_("Sam wants to know if you're a doctor. I said no. He said you look at people like one. He's nine."),
    L_("Sol came in. First time in forty years, he said. Ordered coffee. Left a dollar and a pawn ticket. I don't know what that means either.", () => G.chars.sol && G.chars.sol.stage >= 2),
    L_("The sign hums now. It used to buzz. There's a difference. Ask anybody who's slept above it.", () => G.chars.nadia.signFixed),
    L_("There's a kid who buys one coffee and sits four hours. Hood up. I let him. Somebody let me, once.", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("Rent day is a Tuesday. It's always a Tuesday. God made Tuesdays for landlords.", () => !G.chars.nadia.saved && !G.chars.nadia.closed, 30, 59),
    L_("I made rent and then I cried in the walk-in for ten minutes. Sam thinks I was counting eggs.", () => G.chars.nadia.saved),
    L_("Mrs. Ortega sells tamales out of the booth by the window on Sundays. I take ten percent in tamales. Best deal on the street."),
    L_("The rain gets in under the door. I've got a towel there. Sam calls it the moat."),
    L_("You eat like somebody who forgot how. Slow down. The soup's not going anywhere."),
    L_("Don't get sentimental on me. I've got a diner to run and you've got a face that's gone pale. Eat.", null, 60),
    L_("Whatever the doctor said, she said it to you. She didn't say it to me. In here you're a regular. That's all.", null, 45),
  ],
  nora: [
    L_("Night shift does a thing to your sense of time. It's Tuesday for me. Whatever it is for you."),
    L_("The elevator made a noise today like a man clearing his throat. I said 'excuse you.' It stopped. I'm taking credit."),
    L_("There's a man on the ward who thinks I'm his daughter. I've stopped correcting him. His daughter's not coming."),
    L_("Amos asked me what a nurse does when she's off. I said I lie down. He said that's what he does too. We're colleagues.", () => G.chars.amos.met),
    L_("Nadia's pie at midnight is medically inadvisable. I'm a nurse. I've had it four times.", () => !G.chars.nadia.closed),
    L_("The girl at Lin's keeps back the good orange for me. Nobody's kept anything back for me since my brother."),
    L_("Take the pills. I can hear when you haven't. Through the wall. It's a different cough.", () => G.day - (G.lastPill || 1) >= 2),
    L_("I sat with the old man on the bench. Walter. He told me about type. I understood none of it. It was wonderful.", () => !G.chars.walter.dead),
    L_("The old man on the bench died in his sleep. I checked the paper. That's the good way. I say that as a professional.", () => G.chars.walter.dead),
    L_("I've got a pulse oximeter in my bag and I'm not going to use it on you unless you ask. I'm going to want to."),
    L_("412 and 411. I looked it up; the building was a hotel once. We're sharing a wall that's heard everything."),
    L_("Twelve-hour shift, and then the hallway, and then I stand at my door for a second because I forgot I get to go in."),
    L_("The suit doesn't fool me. I've seen you cough in it.", () => G.flags.vp || G.flags.manager),
    L_("Amos moved into the basement. I brought him a lamp. He acted like I'd brought him the moon.", () => G.chars.amos.room),
    L_("The kid with the hood. I gave him a sandwich Tuesday. He gave it back with a bite gone. Pride. I know pride.", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("My brother liked the rain. I didn't. Now I do. That's how it goes; you inherit their weather."),
    L_("You look like my patients look when they've decided something. Don't decide anything without telling the wall first.", null, 40),
    L_("If you ever can't get to the door, bang. Twice. I'll come through the wall if I have to; I've done worse on shift.", null, 50),
    L_("I'm not going to tell you to rest. I'm going to tell you I'm off Thursday and I've got tea.", null, 60),
    L_("Whatever happens, you had a neighbor. Put that on the form somewhere.", null, 75),
  ],
  emmett: [
    L_("The lake freezes from the edges in. People think it's the middle. It's never the middle."),
    L_("I catch, I clean, I eat, I sleep. Four verbs. A man doesn't need more than four."),
    L_("The county man came once. Looked at the cabin. Looked at me. Wrote something down and left. That was 2011."),
    L_("City people cast like they're throwing something away. It's the opposite. You're putting it somewhere."),
    L_("The bus driver waves. Every Sunday. I don't wave back and he keeps doing it. That's a kind of friend."),
    L_("There's a fella brings his father out on the van. Old man in a chair, holds a rod. Doesn't catch anything. Doesn't need to.", () => G.flags.pryorDock),
    L_("Ortega. The tamale woman. She calls me 'the fish man.' I've been called worse by better."),
    L_("Eight months, the doctor said. I've had two hundred and thirty. I stopped doing the arithmetic; the arithmetic never did anything for me."),
    L_("The boat leaks. Has for years. I bail. You'd be surprised how much of a life is bailing."),
    L_("My father fished. Badly. He'd talk the whole time. I loved it; I'd have listened to him read a phone book."),
    L_("The perch don't know it's Sunday. That's the nicest thing about perch."),
    L_("Your cough's a wet one. Mine was dry. I don't know which is better. Neither did the doctor, in the end."),
    L_("Take the big one home. I've got a lake. You've got a stove and a night."),
    L_("There's a heron works the north shore mornings. Twenty years. We've never spoken. Best neighbor I've had."),
    L_("I wrote Lena a letter once before. 2009. Burned it. Ash floats; I watched it go out past the point.", () => G.chars.emmett.stage >= 2),
    L_("She tied a clinch knot. First try. I taught her that when she was eight. It stayed in her hands nineteen years.", () => G.chars.emmett.lenaCame),
    L_("You've got the wrist now. Don't let anybody tell you it's the arm."),
    L_("Ninety-nine days is about three hundred casts if you come every Sunday. I did the math. I said I don't do math. I lied."),
    L_("Cabin's warm. Porch is warmer, some nights; the lake holds the day's heat and gives it back slow."),
    L_("Whatever the number is, the lake doesn't know it. Come out. Fish. That's the whole prescription.", null, 60),
  ],
  sol: [
    L_("Forty-one years and three break-ins. All three took the wrong things. Nobody takes the ledger."),
    L_("A man brought in a wedding ring last week. Said it was his mother's. It was his. I wrote down 'mother's.'"),
    L_("The trumpet's been in the window since 1994. I moved it into the light once for a girl who was drawing it. Then I moved it back.", () => G.chars.mei.stage >= 1),
    L_("The old man from the bench pawned a watch in '88 and redeemed it in '88. Same week. Only time anybody ever came back that fast.", () => G.chars.walter.met),
    L_("Your building's nurse sold me a stethoscope. Then she bought it back. Then she sold it. She's the ledger's most interesting page.", () => G.chars.nora && G.chars.nora.met),
    L_("Reed's tools sat here two years. Good tools. A man's tools sitting is the saddest thing in this business, and it's a sad business."),
    L_("I don't lend on wedding dresses. It's a rule. It's the only rule I never broke, and I've broken the rest twice."),
    L_("The kid on the poster. Marsh. His brother comes in and looks at the wall. Doesn't buy. I don't charge for looking; that's the one free thing here.", () => G.chars.theo && !G.chars.theo.reunited),
    L_("The poster's down. The brother took it. Left the tape. I've left the tape.", () => G.chars.theo && G.chars.theo.reunited),
    L_("A watch says the time. A pawned watch says a date. Everything in here says a date."),
    L_("Nadia came in. Ordered nothing; I don't sell food. She just wanted to see the trumpet. Everybody wants to see the trumpet.", () => G.chars.nadia.stage >= 1),
    L_("Sunday. Nobody pawns on a Sunday. They pawn on Monday, what they promised God on Sunday they wouldn't.", () => G.day % 7 === 0),
    L_("You've got the look. Not the buying look. The holding look. I know the difference from across a street."),
    L_("My father ran this counter. His father before him sold buttons. I've got a jar of them. Nobody's ever asked."),
    L_("The ledger's got four hundred and twelve names. One's yours. I noticed the number. I notice numbers."),
    L_("The tools went home. Reed came in for them himself, first thing. Didn't say anything. Put his hand flat on the case a minute.", () => G.chars.amos.tools),
    L_("A suit like that came through here once. Owner never came back. I'm not saying anything. I'm saying it once came through.", () => G.flags.vp),
    L_("The heater sold. Whoever's got it, I hope they're warm. That's as much as I let myself hope, in here."),
    L_("I close at six. I've closed at six for forty-one years. The day I don't close at six, call somebody."),
    L_("Come in when it's raining. Nobody buys in the rain and I'd rather the door opened for a face than a sale.", null, 50),
  ],
  jo: [
    L_("Micah asked if you have a dog. I said I don't know. He said that's a weird thing not to know about your brother. It is."),
    L_("I drove past the house. The new people painted the door red. I sat in the car a while. Then I went home."),
    L_("Dad's cards are on the kitchen table. I've been meaning to play. Nobody in this house cheats well enough."),
    L_("I looked up your street. Harlan. There's a diner. Is the pie any good? Don't answer that, I know that face."),
    L_("The kids are asleep. The TV's off. I'm sitting on the kitchen floor with the phone and it's fine. It's actually fine."),
    L_("I found the treehouse photo. Dad's. You're on the ladder and I'm at the bottom telling you to come down. Some things don't change."),
    L_("I'm not going to ask about the doctor. I'm going to ask what's out your window. Rain? It's always rain with you."),
    L_("Micah made you a card. It's a fish. I don't know why a fish. He was very clear it was for you."),
    L_("I burnt dinner tonight thinking about the house. Not the sale. The kitchen. You at the counter, eleven, eating cereal out of the box."),
    L_("Six years is a number. It's not a wall. I keep telling myself that. It's almost working."),
    L_("You called. I'm going to say that to the kids at breakfast like it's the weather. 'Your uncle called.'", () => Jo.J().calledBack > 0),
    L_("I'm coming Sunday. I'm not asking. I've already bought the ticket and I don't do refunds.", () => Jo.J().coming && !Jo.J().visited),
    L_("The room's too small. I said I wouldn't say anything. I'm saying it on the phone, which doesn't count.", () => Jo.J().visited),
    L_("Half the coffee can is still in my glove box. I'm going to keep bringing it until you take it or I run out of gas.", () => Jo.J().visited && !Jo.J().money),
    L_("I told Micah about the eighty dollars. He wanted to know what you bought. I said I'd ask. What did you buy?", () => Jo.J().money),
    L_("Go to bed. I can hear you not going to bed. It's a family sound."),
    L_("I'm not crying. The line's bad. It's a bad line. It's been a bad line for six years."),
    L_("There's a woman at your building who answered once when I called. A nurse. She said you were fine in a voice that meant she'd checked.", () => G.chars.nora && G.chars.nora.trust >= 3),
    L_("Whatever the number is, I've got the number now too. I'm counting with you. From here. That's allowed.", null, 50),
    L_("Say something. Anything. Say 'goodnight, Jo.' I want to hear it once more before I hang up.", null, 70),
  ],
  doctor: [
    L_("Weight?  ...Down. Eat. I don't care what. Calories are calories at this point."),
    L_("The cough suppressant is not a cure. I know you know. I'm required to say it, and I'd say it anyway."),
    L_("Your oxygen's holding. That's the word. Holding. I'll take holding."),
    L_("Sleep in a bed. Not a bench. I can tell a bench from a bed by the way a patient sits down.", () => G.memories.includes('rough')),
    L_("There's a trial in Baltimore. It's closed. I'm telling you so you don't read about it and think I hid it."),
    L_("Nights are worse. They're always worse. Sit up with two pillows; it's not nothing."),
    L_("I'm going to listen to your chest and I'm going to make a face. Ignore the face. The face is for me."),
    L_("The refill's twenty dollars because the pharmacy charges me twenty-two. I'm not a business. Don't tell the board."),
    L_("Rain's bad for you. I can't prescribe a different city."),
    L_("You've got a good heart. Clinically. The rest of you, we're managing."),
    L_("If you're working the dock, lift with your legs and stop at the first cough. Not the third. The first."),
    L_("You look better. I hate saying that; it never means anything. You look better."),
    L_("Ninety-nine was an estimate. I said that. I say it every time and every patient hears a promise. I don't know how to say it differently."),
    L_("Your neighbor, the nurse. She called me. Asked what she could do. I said keep doing it. I don't know what 'it' is. She does.", () => G.chars.nora && G.chars.nora.trust >= 3),
    L_("The bloodwork's back. Nothing new. In my line 'nothing new' is a good day."),
    L_("Take the pills at the same time each day. The body likes a schedule. It's the only thing it's ever asked of you."),
    L_("There's a form for what you want done with... afterward. It's in the drawer. Take it when you want it. Not before."),
    L_("I've had six patients on this number. Two beat it. I'm not saying that to give you hope; I'm saying it because it's the data."),
    L_("Sit. Breathe. Again. Slower. ...Okay. That's all I've got today and it's more than it sounds like.", null, 60),
    L_("Whatever you're doing with the days, keep doing it. Clinically. The numbers say it's working better than the pills.", null, 45),
  ],
  busker: [
    L_("Guitar's got five strings. The sixth is a metaphor. That's what I tell people. It's actually just broken."),
    L_("Rain's good for tips. People feel guilty in the rain. I'm not proud of knowing that."),
    L_("The old man on the bench requested a song once. 'Anything from 1962.' I played something from 1962. He said it was wrong. It was.", () => !G.chars.walter.dead),
    L_("The girl at the market draws me. I've seen the sketches through the window. She gets the hands right. Nobody gets the hands."),
    L_("I wrote a song about the dumpster. It's a love song. The dumpster's not into it."),
    L_("The nurse from your building hums. Off-key, every time. I've started playing in her key. She hasn't noticed."),
    L_("Theo liked the rain songs. Only the rain songs. I've got eleven now. I'm writing them for a kid who isn't here to hear them.", () => G.chars.theo && !G.chars.theo.reunited),
    L_("Theo's on my couch. He snores. I never knew he snored. There's a lot I never knew.", () => G.chars.theo && G.chars.theo.reunited),
    L_("Amos taught me a chord. Said he learned it on a roof. I don't know how you learn a chord on a roof and I didn't ask.", () => G.chars.amos.met),
    L_("Nadia lets me play inside when it pours. I play quiet. Quiet's harder than loud; nobody tells you that.", () => !G.chars.nadia.closed),
    L_("Sunday's dead. Everybody's somewhere else. I play for the pigeons. The pigeons tip in pigeon.", () => G.day % 7 === 0),
    L_("The case has forty cents in it and one of them's a button. Somebody tipped a button. I'm keeping the button."),
    L_("A song is just a thing you say twice because once wasn't enough."),
    L_("The strings you gave me are on. They sound like a different instrument. Same songs. Better lies.", () => G.flags.gaveStrings),
    L_("The old man's gone. I've been playing his 1962 song. Right this time. Somebody should hear it right.", () => G.chars.walter.dead),
    L_("I've got a song about you. It's not finished. It doesn't have an ending yet. I'm in no hurry."),
    L_("Cal. That's the name. Nobody asks. You asked. Cal."),
    L_("The 14 stops here Sundays. I play the bus a song when it pulls in. The driver hates it. Pays a dollar every time."),
    L_("There's a kid who comes and doesn't tip and doesn't leave. That's my favorite kind. That's what I was."),
    L_("Whatever's coming, I'll play you out. That's not morbid. That's a musician's whole promise.", null, 70),
  ],
  granny: [
    L_("Hector fixed every radiator on the fourth floor. Every one. Now they bang like they're looking for him."),
    L_("Sixty tamales, Sunday. Forty on the bus, twenty for the building. The building never pays. The building's family."),
    L_("That man by the stoop. Amos. I've fed him since April. He says thank you every time like it's the first.", () => !G.chars.amos.dead),
    L_("The nurse in 411 checks my blood pressure in the hall. I don't ask. She just takes my arm. Good girl.", () => G.chars.nora && G.chars.nora.met),
    L_("The old man on the bench and my Hector went to the same school. Different years. Same nuns.", () => !G.chars.walter.dead),
    L_("The girl at Lin's charges me for three oranges and gives me four. Her mother knows. Her mother pretends."),
    L_("You're too thin. I say it to everyone. To you I mean it."),
    L_("The elevator ate my grocery bag in 2003. I've taken the stairs since. I'm eighty-one. The stairs know me."),
    L_("Sundays the marina. Mondays the church. Tuesdays I sit. A woman needs a day to sit."),
    L_("The diner does my tamales in the booth by the window. Ten percent. Nadia counts in tamales. Smart girl.", () => !G.chars.nadia.closed),
    L_("There's a kid with a hood on the corner who won't take food. Pride. His mother must be sick with it.", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("The stone's grey. Grey, not black. Black shows the rain. Hector hated a thing that showed the rain.", () => G.flags.ortegaStone),
    L_("Your sister called the building once. Asking about you. I said you were a good boy. I don't know you well; I know a good boy.", () => Jo.J().stage >= 1),
    L_("The pharmacy calls the wrong apartment. Always 412. Somebody wrote it down wrong in 1998 and nobody's fixed it since."),
    L_("I've buried a husband and two brothers and I still can't carry a bag of oranges. God has a sense of humor."),
    L_("Eat. I don't care what you say. Eat. Eat it in front of me so I know."),
    L_("The fish man at the lake calls me the tamale woman. I call him the fish man. We're very formal."),
    L_("Amos carried the cooler off the bus for me last Sunday. A roofer! Complaining about a cooler!", () => G.chars.amos.met && G.day >= 14),
    L_("When my Hector was sick I fed the whole floor. It's what the hands do when the heart can't."),
    L_("You've got people. I see them. Don't tell me you don't; I've got eyes and a window on the street.", null, 50),
  ],
  sam: [
    L_("Mom says you're a regular. What's a regular? Are you regular? You don't look regular."),
    L_("I'm doing fractions. Three-quarters of a pie is more than half. I checked with an actual pie."),
    L_("The old man on the bench said I'll be a typesetter. I don't know what that is. He said nobody does anymore.", () => !G.chars.walter.dead),
    L_("Amos taught me to whistle with two fingers. Mom said not inside. I do it inside.", () => G.chars.amos.met),
    L_("The nurse lady eats pie standing up. I told her to sit. She said nurses don't sit. Is that true?", () => G.chars.nora && G.chars.nora.met),
    L_("I drew the diner for school. You're in it. You're mostly a coat. Sorry."),
    L_("Do you know how to do a clinch knot? The fish man on the bus does. I want to fish. Mom says when I'm ten.", () => G.chars.emmett && G.chars.emmett.met),
    L_("The busker played a song about rain. I told him it's always raining so it's not really about anything. He said that's the point. Adults."),
    L_("I'm supposed to be doing homework. This is homework. You're helping. Don't tell Mom."),
    L_("The moat's back. The towel by the door. I named it the moat. Mom uses my name for it now, which means I won."),
    L_("You cough like the man in 4B. He got better. Mostly. I'm just saying he got better."),
    L_("Checkers. Now. I'll go easy. I won't go easy.", () => G.inv.checkers),
    L_("Mom cried in the walk-in. She said eggs. It wasn't eggs. It's okay; it was the good crying.", () => G.chars.nadia.saved),
    L_("Why do you have a suit? Are you rich? Mom says don't ask people if they're rich. I asked anyway.", () => G.flags.vp),
    L_("Amos works in the back now. He sings. He doesn't know I can hear. He's not good. I like it.", () => G.chars.amos.job === 'diner'),
    L_("I'm nine and three-quarters. That's a fraction. See? I use them."),
    L_("The kid in the hood came in and Mom gave him soup and he didn't say thank you and Mom said that's fine. Why is that fine?", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("Are you going to be okay? Mom says ask. Then she says don't ask. I'm asking."),
    L_("I made you a card. It's in my bag. You can't have it yet. It's not for now.", null, 60),
    L_("When you're better you have to take me fishing. That's a deal. I shook on it for you.", null, 40),
  ],
  worker: [
    L_("Six a.m. I don't care what the sky's doing. The trucks don't either."),
    L_("A clean stack's a clean stack. I don't say thanks. I say tomorrow. That's thanks."),
    L_("Reed's early every day. Every day. Twenty years in this yard I've never had a man early every day.", () => G.chars.amos.job === 'dock'),
    L_("Owner walks through Fridays. Don't look at him. He likes it when they don't look."),
    L_("Coughing on my dock is fine. Dropping a crate on my dock is not. Know the difference."),
    L_("My father ran this dock. Same clipboard. I've replaced the paper. That's it."),
    L_("The trailer's got a heater. It's got one setting: too hot. Managers earn the too hot.", () => G.flags.manager),
    L_("Nine sharp for the chair. Not six. Executives don't do six. I do six. I've always done six.", () => G.flags.vp),
    L_("Payroll came down lighter. I don't ask why. I read the names and I know why.", () => (G.flags.cutCount || 0) > 0),
    L_("There's a kid asks for day work some mornings. Hood up. I say sixteen and ID. He walks. I hate it every time.", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("Sunday the yard's closed. I come in anyway. Count the pallets. They're all there. I go home."),
    L_("The 14's back Sundays. Driver used to work here. Couldn't lift. Could drive. Everybody's got the one thing."),
    L_("You stack like a man who's done it before. Or a man who's read about it. Either way the pallet's straight."),
    L_("Water's in the office. Take it. I've seen men fall over out here for pride and pride don't pay."),
    L_("The old man from the bench came by once for a job. 1991. I said too old. He said fair. I still think about it."),
    L_("Don't thank me. Thank the pallet. It's the only honest thing on the lot."),
    L_("Reed's on the day sheet in your writing. That's a thing you did. I don't say that about many things.", () => G.flags.hiredAmosAsManager),
    L_("I was cut once. Different yard. Guy who did it didn't look at me. I look. It's the least you can do and it's not enough."),
    L_("You're slower this week. Stack lower. I'd rather a low stack than a man on the ground.", null, 60),
    L_("Whatever's wrong with you, the crates don't care and neither do I, in the good way. Tomorrow.", null, 40),
  ],
  pryor: [
    L_("The spreadsheet's my father's accounts. I keep them. He doesn't know. It's the last thing I can do that looks like something."),
    L_("The home has a bell for meals. He stands up for the bell. Forty years of factory bells. The body remembers what the mind lets go."),
    L_("I bring him the paper. He reads the same page. Every Sunday, the same page. Sports from 2004. I've stopped buying a new one."),
    L_("The van driver's name is Reggie. He's the best man I know and I've known him eleven minutes at a time."),
    L_("My wife says I don't have to come every week. She's right. I come every week. Both things."),
    L_("He called me by my brother's name today. I don't have a brother. I let it stand."),
    L_("Ortega sells him a tamale every Sunday. He can't eat it. He holds it. She knows. She sells it anyway.", () => G.flags.ortegaBus >= 1),
    L_("The pier's the first place in two years I've seen him look at something instead of through it.", () => G.flags.pryorDock),
    L_("I closed the laptop and I haven't opened it on the bus since. My boss thinks I've had a breakdown. I've had a Sunday."),
    L_("I used to fish with him. I'd forgotten that. Emmett said 'your father fished' like it was obvious and something fell into place."),
    L_("He said 'Sunday.' I keep telling people. They nod. They don't know. It's the whole word."),
    L_("The 14 smells like diesel and tamales and it's the best hour of my week. I don't say that at work."),
    L_("I've started sitting in the same seat. Third from the back. The driver saves it. I don't know how he knows."),
    L_("You look like you're on the bus for a reason too. Everybody on the 14's got a reason. Nobody's got a laptop."),
    L_("Forty minutes. I count it now the other way; not how long till I can leave, how long I've got."),
    L_("He held the rod for an hour and I held the chair and neither of us caught anything and it was the best day I've had since I was nine."),
    L_("My son wants to come. He's seven. I said next month. I've been saying next month for a year. Next Sunday."),
    L_("I don't know your name. I've told you my whole life and I don't know your name. That's the 14."),
    L_("Whatever you're taking the bus for, I hope it's a chair on a pier. I hope it's exactly that.", null, 40),
    L_("If I don't see you next Sunday I'll assume you're at the lake already. That's what I'll assume.", null, 70),
  ],
  theo: [
    L_("The river's the same every morning. That's why I come. Nothing else is."),
    L_("Cal thinks I ran from him. I ran from the house. He was just in it."),
    L_("The kid at the market gave me a pencil. I don't draw. I've kept it."),
    L_("The homeless guy by 412 shares his cardboard when it pours. Doesn't say anything. Just moves over.", () => !G.chars.amos.dead),
    L_("The nurse gave me a sandwich. I gave it back. Then I went around the corner and was sorry for an hour."),
    L_("I'm not lost. The poster says lost. I know exactly where I am. It's the house that's lost."),
    L_("Cal's couch is a foot too short and the springs know my name. I've never slept better. Don't tell him.", () => G.chars.theo.reunited),
    L_("He plays the rain songs when he thinks I'm asleep. I'm never asleep. I count them. Eleven now.", () => G.chars.theo.reunited),
    L_("The old man on the bench told me to go home. Everybody says that. He said it like he'd tried it and it hadn't worked.", () => !G.chars.walter.dead),
    L_("Sol lets me stand in the doorway when it rains. Doesn't look up. That's the nicest thing anyone's done all month."),
    L_("The diner lady gives me soup and doesn't want anything. That's harder to take than the ones who want something."),
    L_("The foreman won't hire me. Sixteen and ID. I've got one of those."),
    L_("Rain's good. Rain means nobody looks at you. Nobody looks at anything."),
    L_("My mom's poster. Her handwriting on the phone number. I can't look at it and I can't walk past it either."),
    L_("Cal's got a song with me in it. He thinks I don't know. It's got a bus in it. I've never been on a bus."),
    L_("I'm going to go back. Not yet. Yet's the thing I can't get past."),
    L_("You look sick. Not like a cold. Like the way Dad looked. Sorry. I don't have a nicer way."),
    L_("The dog by the fence lets me sit with it. Doesn't want anything. That's why."),
    L_("Cal says you found him. He says it like you did something. All you did was look at a wall.", () => G.chars.theo.reunited),
    L_("If you see me at the river and I don't say anything, that's not nothing. That's me saying something.", null, 30),
  ],
  lena: [
    L_("He talks about you like you're the weather. 'The one who carried it.' That's a whole title."),
    L_("The cabin's exactly how I pictured it. I pictured it a lot. Nineteen years of picturing."),
    L_("I brought a rod. My own. He looked at it like I'd brought a child."),
    L_("The knot. My hands knew it before I did. That's what he gave me and forgot he gave me."),
    L_("June. I said June. He's already counting. I can see him counting."),
    L_("The letter's in my glove box. I read it at red lights. Every red light between here and Columbus."),
    L_("He apologized. Badly. It was the best bad apology I've ever heard. I'm going to keep it."),
    L_("I'm forty-one. I felt eight on this pier. I don't know what that is. It's not bad."),
    L_("There's a heron. He named it. He won't tell me the name. That's the most Dad thing that's ever happened."),
    L_("Thank you. I know I said it. I'm going to be saying it for a while."),
    L_("The boat leaks. He says it's always leaked. I'm buying him a new one and he's going to hate it and use it."),
    L_("I've got his handwriting on my fridge now. My kids ask who. I say Grandpa. It's the first time I've said that."),
    L_("He said 'sorry I lived.' To my face. I hit him. Gently. Then I didn't let go."),
    L_("Nineteen years and the first thing he asked was whether I still hated oatmeal. I do. He remembered."),
    L_("You look like you've got your own number. I can see it. I hope somebody carries yours."),
    L_("Sunday after next I'm bringing the kids. He doesn't know. Don't tell him. He'll clean the cabin again."),
    L_("The line goes out like it was always going to. That's his line. He's been saying it since I was six. It's still true."),
    L_("I'm going to sit here till the bus. He's going to pretend to fish. I'm going to pretend to fish. It's a whole language."),
    L_("The last line of the letter's the only line I needed. He wrote a page about fish so he could get to it. I get that now."),
    L_("Whatever you did, it was carrying it. That's all. That's everything. Both.", null, 30),
  ],
  owner: [
    L_("The chair's the chair. Somebody sits in it. I don't care about the name; I care about the nine."),
    L_("Payroll's a list. Lists don't have faces. The day they get faces, get out of the chair."),
    L_("My father built this dock with men he knew by name. I can't afford to know names. That's not cruelty; it's the margin."),
    L_("You cough in my office again and I'll have the chair steam-cleaned and bill it to you."),
    L_("Nine sharp is a courtesy. I've fired men for eight fifty-nine."),
    L_("Kowalski's loyal. Loyal's expensive. Do the math on it before I do."),
    L_("The suit fits. The suit's the only thing in this building I've never had to cut."),
    L_("Whatever you're saving for, save faster. The chair doesn't wait and neither do the numbers.", null, 30),
  ],
  danny: [
    L_("Foreman's in a mood. Foreman's always in a mood. It's the same mood."),
    L_("Reed's been here since five. Five! I said, Amos, the gate's not open. He said he knows.", () => G.chars.amos.job === 'dock'),
    L_("The kid on the corner asked for day work. Foreman said ID. Kid walked. Same thing every week.", () => G.chars.theo && !G.chars.theo.reunited && G.day >= 12),
    L_("Smoke break's four minutes. I take six. That's my whole rebellion."),
    L_("You're the one from 412? Amos talks about you like you're the mayor."),
    L_("There's a manager job going. Twelve hours in a trailer. I'd rather stack. Stacking ends."),
    L_("Sunday the yard's shut and I come in anyway. Habit. Foreman's here too. We don't talk. It's nice."),
    L_("Whoever's got the chair upstairs, tell them the coffee machine's been broken since March.", () => G.flags.vp || G.flags.manager),
  ],
};
// pick a line the character has not said lately; base = the lines the scene already had
function fresh(id, base) {
  G.seen = G.seen || {}; const seen = G.seen[id] || (G.seen[id] = []);
  const ch = G.chars && G.chars[id]; const shy = ch && (ch.cold || ch.met === false);   // strangers and the cold-shouldered keep to their own lines
  const extra = shy ? [] : (FRESH[id] || []).filter(x => G.day >= x.d0 && G.day <= x.d1 && (!x.need || safeNeed(x.need))).map(x => x.t);
  const pool = (base || []).concat(extra); if (!pool.length) return '';
  let cand = pool.filter(l => !seen.includes(l));
  if (!cand.length) { seen.length = 0; cand = pool; }
  const l = pick(cand); seen.push(l); if (seen.length > Math.max(6, pool.length - 2)) seen.shift();
  return l;
}
function safeNeed(f) { try { return !!f(); } catch (e) { return false; } }
